import { afterEach, describe, expect, it, vi } from 'vitest';

import {
  describeRankingList,
  fetchPersonRankingHistory,
  fetchSnapshot,
  rankingListPath,
  RankingSnapshot,
} from './rankingsApi';

function snapshot(overrides: Partial<RankingSnapshot> = {}): RankingSnapshot {
  return {
    snapshotId: 'a3f1c2d4-0000-4000-8000-000000000001',
    policyName: 'USTA Junior 2026',
    policyVersion: '2026.01',
    asOfDate: '2026-08-12',
    generatedAt: '2026-08-12T11:38:39.420Z',
    entryCount: 20805,
    rollingPeriodDays: 365,
    ...overrides,
  };
}

describe('describeRankingList', () => {
  it('names a list from the axes it is actually split on', () => {
    const label = describeRankingList(
      snapshot({ bodyId: 'USTA', ageCategoryCode: 'U18', gender: 'MALE', discipline: 'SINGLES' }),
    );
    expect(label).toBe('USTA · U18 · Male · Singles');
  });

  it('omits an axis the list is not split on rather than saying "unknown"', () => {
    // NULL means "not split on this axis" -- the reading migration 0010 gave
    // these columns. A list that splits on nothing is legitimately just its
    // body's name, and an "Unknown" fragment would assert a missing fact that
    // is not missing.
    const label = describeRankingList(
      snapshot({ bodyId: 'CTS', ageCategoryCode: null, gender: null, discipline: null, levelCode: null }),
    );
    expect(label).toBe('CTS');
  });

  it('falls back to the policy name when a body has not been stamped', () => {
    // Pre-0010 snapshots have no body_id at all.
    expect(describeRankingList(snapshot({ bodyId: undefined, ageCategoryCode: null, gender: null }))).toBe(
      'USTA Junior 2026',
    );
  });

  it('carries an NTRP level through', () => {
    expect(describeRankingList(snapshot({ bodyId: 'USTA', levelCode: '4.0', gender: 'FEMALE', ageCategoryCode: null }))).toBe(
      'USTA · Female · 4.0',
    );
  });
});

describe('rankingListPath', () => {
  it('addresses the stored list, and encodes the id', () => {
    expect(rankingListPath('abc-123')).toBe('/rankings/list/abc-123');
    expect(rankingListPath('a/b')).toBe('/rankings/list/a%2Fb');
  });
});

describe('fetchPersonRankingHistory', () => {
  afterEach(() => vi.unstubAllGlobals());

  function stubFetch(response: unknown, ok = true, status = 200) {
    const spy = vi.fn().mockResolvedValue({ ok, status, json: async () => response });
    vi.stubGlobal('fetch', spy);
    return spy;
  }

  it('reads the person route under the rankings prefix', async () => {
    // The prefix is not cosmetic: the CFS proxy rewrites /api/rankings/<tail>
    // to /rankings/<tail>, so anything mounted elsewhere upstream is
    // unreachable from this client entirely.
    const spy = stubFetch({ data: [], pagination: { limit: 60, offset: 0, total: 0 } });
    await fetchPersonRankingHistory('2010688342', { limit: 60 });

    expect(spy).toHaveBeenCalledTimes(1);
    const url = spy.mock.calls[0][0] as string;
    expect(url).toBe('/api/rankings/person/2010688342/history?limit=60');
  });

  it('encodes a person id that is not url-safe', async () => {
    const spy = stubFetch({ data: [], pagination: { limit: 60, offset: 0, total: 0 } });
    await fetchPersonRankingHistory('usta/2010688342');
    expect(spy.mock.calls[0][0]).toBe('/api/rankings/person/usta%2F2010688342/history');
  });

  it('returns an empty history rather than throwing when a player has none', async () => {
    // The common case in production today: snapshots are generated by an
    // explicit step, so most players have no published list yet. That is a
    // fact to render, not a failure to catch.
    stubFetch({ data: [], pagination: { limit: 60, offset: 0, total: 0 } });
    const result = await fetchPersonRankingHistory('nobody');
    expect(result.data).toEqual([]);
    expect(result.pagination.total).toBe(0);
  });

  it('throws on a transport failure, so the caller can distinguish it from empty', async () => {
    stubFetch({}, false, 502);
    await expect(fetchPersonRankingHistory('anyone')).rejects.toThrow('HTTP 502');
  });
});

describe('fetchSnapshot', () => {
  afterEach(() => vi.unstubAllGlobals());

  it('pages the list body', async () => {
    const spy = vi.fn().mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => ({ snapshot: snapshot(), entries: [], pagination: { limit: 200, offset: 200, total: 20805 } }),
    });
    vi.stubGlobal('fetch', spy);

    const result = await fetchSnapshot('snap-1', { limit: 200, offset: 200 });
    expect(spy.mock.calls[0][0]).toBe('/api/rankings/snapshots/snap-1?limit=200&offset=200');
    // The total is the size of the LIST, not of the page -- 20,805 is a real
    // USTA Boys' 18 standings list.
    expect(result.pagination.total).toBe(20805);
  });
});
