import { defineConfig, devices } from '@playwright/test';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

// Repo root — this config lives in `<root>/e2e/`. Playwright runs
// `webServer.command` with cwd = the config's directory by default, so we must
// point it back at the repo root or vite roots itself in `e2e/` (no index.html
// / vite.config.ts) and the readiness poll never resolves.
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

/**
 * Hermetic Playwright config for courthive-public.
 *
 * The public viewer is a pure read-only API consumer — every page hydrates
 * from `baseApi.post('/factory/...')` against the competition-factory-server.
 * These e2e tests never touch a real server: `helpers/routes.ts` intercepts
 * every `/factory/*` and `/provider/*` request with `page.route` and fulfills
 * it from fixtures generated by `tods-competition-factory`'s `mocksEngine`
 * (see `helpers/fixtures.ts`). That keeps the suite deterministic, fast, and
 * CI-friendly — no CFS, Redis, or Postgres required.
 *
 * The Vite dev server is launched by Playwright on :5174 (strictPort matches
 * vite.config.ts). `vite` is invoked directly rather than `pnpm start` to
 * skip the `--open` browser launch and the interactive config check.
 */
const PORT = 5174;
// Bind/poll on an explicit IPv4 host to avoid any localhost→IPv6 (::1)
// resolution mismatch between vite's bind address and the readiness poll.
const HOST = '127.0.0.1';
const BASE_URL = `http://${HOST}:${PORT}`;

export default defineConfig({
  testDir: './journeys',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: process.env.CI ? [['github'], ['list'], ['html', { open: 'never' }]] : [['list']],
  timeout: 30_000,
  expect: { timeout: 10_000 },
  use: {
    baseURL: BASE_URL,
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },
  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],
  webServer: {
    command: `pnpm exec vite --port ${PORT} --strictPort --host ${HOST}`,
    cwd: ROOT,
    url: BASE_URL,
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
    // The dev server reads VITE_SERVER from .env.development; the API base
    // resolves to localhost which our route mocks intercept regardless.
    env: { BASE_URL: '' },
  },
});
